## first problem




In [0]:
import numpy as np
a = np.random.rand(4,2)
print(a)

[[0.97254805 0.33493797]
 [0.29147949 0.26528189]
 [0.67354801 0.08462112]
 [0.77389845 0.48840445]]


## second problem


In [0]:
def ascending_sort(x):
  rows, cols = x.shape
  for i in range(cols):
      index_min= i+np.argmin(x[0][i:])
      print(index_min)
      temp_val = x[0][i]
      print(temp_val)
      x[0][i] = x[0][index_min]
      print(x[0][i])
      x[0][index_min] = temp_val
      print(x[0][index_min])
  return x

In [0]:
a2 = np.random.rand(1,10)
a2


array([[0.22462554, 0.69729959, 0.48174829, 0.99960235, 0.47757818,
        0.16727243, 0.74766869, 0.41146294, 0.47967081, 0.35020314]])

In [0]:
print(a2[0][3:])
np.argmin(a2[0][3:])

[0.99960235 0.47757818 0.16727243 0.74766869 0.41146294 0.47967081
 0.35020314]


2

In [0]:
ascending_sort(a2)

5
0.22462553610286418
0.16727243454177432
0.22462553610286418
5
0.6972995853971162
0.22462553610286418
0.6972995853971162
9
0.4817482920708357
0.35020313659251145
0.4817482920708357
7
0.9996023522240535
0.4114629360574268
0.9996023522240535
4
0.4775781771161356
0.4775781771161356
0.4775781771161356
8
0.6972995853971162
0.47967081435911385
0.6972995853971162
9
0.7476686856738654
0.4817482920708357
0.7476686856738654
8
0.9996023522240535
0.6972995853971162
0.9996023522240535
9
0.9996023522240535
0.7476686856738654
0.9996023522240535
9
0.9996023522240535
0.9996023522240535
0.9996023522240535


array([[0.16727243, 0.22462554, 0.35020314, 0.41146294, 0.47757818,
        0.47967081, 0.48174829, 0.69729959, 0.74766869, 0.99960235]])

In [0]:
def descending_sort(x):
  rows, cols = x.shape
  for i in range(cols):
      index_min= i+np.argmax(x[0][i:])
      print(index_min)
      temp_val = x[0][i]
      print(temp_val)
      x[0][i] = x[0][index_min]
      print(x[0][i])
      x[0][index_min] = temp_val
      print(x[0][index_min])
  return x

In [0]:
descending_sort(a2)

9
0.16727243454177432
0.9996023522240535
0.16727243454177432
8
0.22462553610286418
0.7476686856738654
0.22462553610286418
7
0.35020313659251145
0.6972995853971162
0.35020313659251145
6
0.4114629360574268
0.4817482920708357
0.4114629360574268
5
0.4775781771161356
0.47967081435911385
0.4775781771161356
5
0.4775781771161356
0.4775781771161356
0.4775781771161356
6
0.4114629360574268
0.4114629360574268
0.4114629360574268
7
0.35020313659251145
0.35020313659251145
0.35020313659251145
8
0.22462553610286418
0.22462553610286418
0.22462553610286418
9
0.16727243454177432
0.16727243454177432
0.16727243454177432


array([[0.99960235, 0.74766869, 0.69729959, 0.48174829, 0.47967081,
        0.47757818, 0.41146294, 0.35020314, 0.22462554, 0.16727243]])

##3rd problem

In [0]:
x= np.array([1,2, 3, 4, 5, 6, 7, 8, 9])
print(x)

[1 2 3 4 5 6 7 8 9]


In [0]:
np.reshape(x, (3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##4th problem

In [0]:
a = np.random.rand(2,3)
a

array([[0.11288289, 0.13576893, 0.63857861],
       [0.90395301, 0.24721243, 0.33555663]])

In [0]:
b= np.random.rand(2,4)
b

array([[0.27416852, 0.42063241, 0.0440389 , 0.27320095],
       [0.88158788, 0.37531577, 0.21307972, 0.96186599]])

In [0]:
# stacking 2 arrays horizontally, need to have same number of rows
np.hstack((a, b))        ## joining horizontally

array([[0.11288289, 0.13576893, 0.63857861, 0.27416852, 0.42063241,
        0.0440389 , 0.27320095],
       [0.90395301, 0.24721243, 0.33555663, 0.88158788, 0.37531577,
        0.21307972, 0.96186599]])

In [0]:
c = np.random.rand(5,4)
c

array([[0.18513116, 0.37950993, 0.60805614, 0.58070155],
       [0.19160996, 0.53072826, 0.84218967, 0.858367  ],
       [0.72909346, 0.99993813, 0.83137246, 0.03786377],
       [0.6179399 , 0.86119414, 0.54935659, 0.7381191 ],
       [0.21713906, 0.36430872, 0.52516043, 0.35180778]])

In [0]:
# stacking 2 arrays vertically, need to have same number of columns
np.vstack((c, b))      ## joining vertically

array([[0.18513116, 0.37950993, 0.60805614, 0.58070155],
       [0.19160996, 0.53072826, 0.84218967, 0.858367  ],
       [0.72909346, 0.99993813, 0.83137246, 0.03786377],
       [0.6179399 , 0.86119414, 0.54935659, 0.7381191 ],
       [0.21713906, 0.36430872, 0.52516043, 0.35180778],
       [0.27416852, 0.42063241, 0.0440389 , 0.27320095],
       [0.88158788, 0.37531577, 0.21307972, 0.96186599]])

## 5th problem

In [0]:
a5 = np.random.randint(2, 20, (3, 4))
b5 = np.random.randint(2, 20, (3, 4))
print('a5 = ' + str(a5))
print('b5 = ' + str(b5))

a5 = [[12 15 16 11]
 [ 3  5  6 15]
 [10 16  4  2]]
b5 = [[ 9  6 16  7]
 [ 6  6  5  3]
 [ 4 11  7 10]]


In [0]:
np.intersect1d(a5, b5)

array([ 3,  4,  5,  6, 10, 11, 16])

##6th problem

In [0]:
a6= np.random.randint(0,20,(5,5))
print (a6)

[[13 12  3 11  8]
 [17 12 19 17 16]
 [12  4 17  3 12]
 [18  4  5  9 11]
 [ 1 13  3  1 12]]


In [0]:
c_max = np.amax(a6, axis =0)
print(c_max )

[18 13 19 17 16]


In [0]:
c_min = np.amin(a6, axis =0)
print(c_min )

[1 4 3 1 8]


In [0]:
r_max = np.amax(a6, axis =1)
print(r_max )

[13 19 17 18 13]


In [0]:
r_min = np.amin(a6, axis =0)
print(r_min )

[1 4 3 1 8]


##7th problem

In [0]:
a7 = np.arange(100)
print(a7)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [0]:
np.mean(a7)

49.5

In [0]:
np.median(a7)

49.5

In [0]:
np.std(a7)

28.86607004772212

##8th problem

In [0]:
from numpy import linalg as LA

In [0]:
a8 = np.random.rand(1,10)
a8

array([[0.42732989, 0.06464925, 0.12754972, 0.39885959, 0.88335392,
        0.95950008, 0.0094969 , 0.38179348, 0.38791854, 0.56118849]])

In [0]:
LA.norm(a8)

1.6353509032342526

## 9th problem

In [0]:
A = np.random.rand(4,3)
A

array([[2.42034619e-01, 1.98426622e-01, 4.01699769e-01],
       [8.47947275e-01, 1.64709990e-02, 4.67148477e-02],
       [5.75978954e-01, 1.02978463e-01, 4.89785339e-04],
       [5.03756486e-01, 9.26949422e-01, 9.58244150e-01]])

In [0]:
print(A.shape)

(4, 3)


In [0]:
B = np.random.rand(4,4,3)
B

array([[[0.95448607, 0.29125181, 0.69096977],
        [0.36451862, 0.50347256, 0.22093045],
        [0.62447092, 0.03390129, 0.07986685],
        [0.7190801 , 0.33646185, 0.52010097]],

       [[0.84779136, 0.10432109, 0.23228598],
        [0.71144913, 0.56240432, 0.41970951],
        [0.81252123, 0.92222859, 0.42589152],
        [0.36746054, 0.02882602, 0.61834777]],

       [[0.63724343, 0.323568  , 0.09064297],
        [0.77819137, 0.43327259, 0.0686763 ],
        [0.33678152, 0.68358991, 0.41904225],
        [0.15744703, 0.40617723, 0.46017893]],

       [[0.21315649, 0.77542102, 0.73002723],
        [0.9964142 , 0.53502158, 0.86516247],
        [0.57495663, 0.73635637, 0.41746535],
        [0.32767772, 0.62427611, 0.85491099]]])

In [0]:
print(B.shape)

(4, 4, 3)


In [0]:
print(B.shape[0])

4


In [0]:
def matrix_mult (x, y):
  c=[0,0,0,0]
  for k in range(x.shape[0]):
    s=0
    for i in range(x.shape[1]):
      for j in range(x.shape[2]):
        c[k] = s = s+x[k][i][j]*y[i][j]
  return c


In [0]:
matrix_mult (B, A)

[2.4297996036452956,
 2.3188779710870193,
 2.0864244508116956,
 3.3629940064661863]