Bootstraps 

In [0]:
import matplotlib
import pandas as pd
import seaborn as sns
import numpy as np

Customer Dataset

In [0]:
#Load CSV file
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab2%20-%20bootstrap/customers.csv')
print(df)

    Day   Millons of pounds in sales
0     1                          2.0
1     2                          8.0
2     3                         20.0
3     4                         13.0
4     5                          5.0
5     6                          9.0
6     7                         10.0
7     8                          8.0
8     9                         22.0
9    10                         10.0
10   11                          2.0
11   12                          4.0
12   13                          7.0
13   14                          9.0


In [0]:
# extracting target column
data = df.values.T[1]
print(data)

[ 2.  8. 20. 13.  5.  9. 10.  8. 22. 10.  2.  4.  7.  9.]


In [0]:
### 2. Calculate and save the mean of the array (this is "data_mean" that is returned by the function)
data_mean = np.mean(data)
print(data_mean)

9.214285714285714


In [0]:
x1 = np.random.choice(data, 9)
print(x1)
x1_mean = np.mean(x1)
print(x1_mean)

[20.  2. 22.  8.  7. 22. 10. 10.  9.]
12.222222222222221


In [0]:
x2 = np.random.choice(data, 9)
print(x2)
x2_mean = np.mean(x2)
print(x2_mean)

[22.  8.  2. 20.  8. 22.  9.  9. 13.]
12.555555555555555


In [0]:
x3 = np.random.choice(data, 9)
print(x3)
x3_mean = np.mean(x3)
print(x3_mean)

[13.  5. 13. 13.  2. 10.  9. 10.  9.]
9.333333333333334


In [0]:
x4 = np.random.choice(data, 9)
print(x4)
x4_mean = np.mean(x4)
print(x4_mean)

[13.  2. 20.  2. 10. 20.  5.  9. 10.]
10.11111111111111


In [0]:
x5 = np.random.choice(data, 9)
print(x5)
x5_mean = np.mean(x5)
print(x5_mean)

[ 2.  4.  8.  7. 22.  2. 13. 10. 13.]
9.0


##Defining Bootstrap_mean function

In [0]:
def boostrap_mean(sample, sampl_size, n_iteration):
  data_array= []
  for i in range (0, n_iteration):
    a = np.random.choice(sample, sampl_size)
    a_mean = np.mean(a)
    #print(a)
    #print(a_mean)
    data_array = np.append(data_array, a_mean)
  #print(data_array)
  data_mean = np.mean(data_array)
  CI= np.percentile(data_array, [2.5, 97.5])
  #print(CI)
  lower, upper = CI
  #print(lower)
  #print(upper)
  return data_mean, lower, upper

In [0]:
boostrap_mean(data, 20, 10)

(8.98, 7.035, 10.93125)

In [0]:
data.shape[0]

14

In [0]:
boot = boostrap_mean(data, data.shape[0], 100)

In [0]:
boot[0]

9.122142857142856

In [0]:
boot[1]

6.308928571428571

In [0]:
boot[2]

12.285714285714286

In [0]:
boots = []
for i in range(100, 100000, 1000):
    boot = boostrap_mean(data, data.shape[0], i)
    boots.append([i, boot[0], "mean"])
    boots.append([i, boot[1], "lower"])
    boots.append([i, boot[2], "upper"])

KeyboardInterrupt: ignored

In [0]:
df_boot = pd.DataFrame(boots, columns=['Boostrap Iterations', 'Mean', "Value"])
sns_plot = sns.lmplot(df_boot.columns[0], df_boot.columns[1], data=df_boot, fit_reg=False, hue="Value")

In [0]:
sns_plot.axes[0, 0].set_ylim(0,)
sns_plot.axes[0, 0].set_xlim(0, 100000)

In [0]:
sns_plot.savefig("bootstrap_confidence.png", bbox_inches='tight')
sns_plot.savefig("bootstrap_confidence.pdf", bbox_inches='tight')

Vehicles dataset

In [0]:
#Load CSV file
df_1 = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab2%20-%20bootstrap/vehicles.csv')
print(df_1)

     Current fleet  New Fleet
0               18       24.0
1               15       27.0
2               18       27.0
3               16       25.0
4               17       31.0
..             ...        ...
244             27        NaN
245             27        NaN
246             32        NaN
247             28        NaN
248             31        NaN

[249 rows x 2 columns]


In [0]:
f_old= df_1.values.T[0]
mean_old = np.mean(f_old)
mean_old

20.14457831325301

In [0]:
f_new= df_1.values.T[1]
f_new

array([24., 27., 27., 25., 31., 35., 24., 19., 28., 23., 27., 20., 22.,
       18., 20., 31., 32., 31., 32., 24., 26., 29., 24., 24., 33., 33.,
       32., 28., 19., 32., 34., 26., 30., 22., 22., 33., 39., 36., 28.,
       27., 21., 24., 30., 34., 32., 38., 37., 30., 31., 37., 32., 47.,
       41., 45., 34., 33., 24., 32., 39., 35., 32., 37., 38., 34., 34.,
       32., 33., 32., 25., 24., 37., 31., 36., 36., 34., 38., 32., 38.,
       32., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, na

In [0]:
f_new= (f_new[~np.isnan(f_new)])
print(f_new)

[24. 27. 27. 25. 31. 35. 24. 19. 28. 23. 27. 20. 22. 18. 20. 31. 32. 31.
 32. 24. 26. 29. 24. 24. 33. 33. 32. 28. 19. 32. 34. 26. 30. 22. 22. 33.
 39. 36. 28. 27. 21. 24. 30. 34. 32. 38. 37. 30. 31. 37. 32. 47. 41. 45.
 34. 33. 24. 32. 39. 35. 32. 37. 38. 34. 34. 32. 33. 32. 25. 24. 37. 31.
 36. 36. 34. 38. 32. 38. 32.]


In [0]:
mean_new = np.mean(f_new)
mean_new

30.481012658227847

In [0]:
len(f_old)
len(f_new)

79

In [0]:
boostrap_mean(f_old, len(f_old), 100)

(20.12096385542169, 19.55572289156627, 20.75813253012048)

In [0]:
boostrap_mean(f_new, len(f_new), 100)

(30.518734177215187, 29.149367088607598, 31.846518987341767)

Permutation testing

In [0]:
# merge both old and new fleet data
concat = np.concatenate((f_old, f_new))
concat 

array([18., 15., 18., 16., 17., 15., 14., 14., 14., 15., 15., 14., 15.,
       14., 22., 18., 21., 21., 10., 10., 11.,  9., 28., 25., 19., 16.,
       17., 19., 18., 14., 14., 14., 14., 12., 13., 13., 18., 22., 19.,
       18., 23., 26., 25., 20., 21., 13., 14., 15., 14., 17., 11., 13.,
       12., 13., 15., 13., 13., 14., 22., 28., 13., 14., 13., 14., 15.,
       12., 13., 13., 14., 13., 12., 13., 18., 16., 18., 18., 23., 11.,
       12., 13., 12., 18., 21., 19., 21., 15., 16., 15., 11., 20., 21.,
       19., 15., 26., 25., 16., 16., 18., 16., 13., 14., 14., 14., 28.,
       19., 18., 15., 15., 16., 15., 16., 14., 17., 16., 15., 18., 21.,
       20., 13., 23., 20., 23., 18., 19., 25., 26., 18., 16., 16., 15.,
       22., 22., 24., 23., 29., 25., 20., 18., 19., 18., 27., 13., 17.,
       13., 13., 13., 30., 26., 18., 17., 16., 15., 18., 21., 19., 19.,
       16., 16., 16., 16., 25., 26., 31., 34., 36., 20., 19., 20., 19.,
       21., 20., 25., 21., 19., 21., 21., 19., 18., 19., 18., 18

In [0]:
#permute it randomly to create a new array
perm = np.random.permutation(concat)
perm

array([18., 13., 14., 16., 16., 32., 13., 36., 25., 28., 32., 30., 22.,
       11., 16., 18., 26., 19., 22., 31., 34., 32., 37., 27., 18., 16.,
       36., 33., 33., 28., 18., 20., 22., 19., 15., 23., 36., 17., 17.,
       17., 21., 23., 15., 33., 24., 16., 24., 16., 16., 21., 19., 12.,
       17., 23., 30., 20., 36., 14., 15., 23., 24., 13., 32., 38., 36.,
       32., 37., 20., 25., 29., 10., 21., 15., 20., 34., 18., 14., 14.,
       19., 33., 15., 34., 13., 13., 25., 16., 15., 18., 31., 26., 30.,
       18., 26., 28., 27., 30., 17., 34., 24., 21., 15., 13., 28., 25.,
       18., 22., 12., 11., 14., 16., 27., 25., 37., 10., 14., 18., 21.,
       38., 19., 34., 12., 34., 31., 15., 20., 14., 19., 31., 34., 15.,
       37., 22., 27., 38., 16., 15., 15., 25., 26., 14., 26., 18., 14.,
       21., 13., 23., 35., 18., 19., 16., 20., 39., 18., 12., 18., 19.,
       28., 21., 14., 13., 19., 22., 19., 24., 18., 27., 13., 27., 24.,
       26., 15., 26., 27., 30., 18., 27., 35., 24., 18., 30., 13

In [0]:
# split the whole data into two array
p_old = perm[:int(len(f_old))]
p_old

array([18., 13., 14., 16., 16., 32., 13., 36., 25., 28., 32., 30., 22.,
       11., 16., 18., 26., 19., 22., 31., 34., 32., 37., 27., 18., 16.,
       36., 33., 33., 28., 18., 20., 22., 19., 15., 23., 36., 17., 17.,
       17., 21., 23., 15., 33., 24., 16., 24., 16., 16., 21., 19., 12.,
       17., 23., 30., 20., 36., 14., 15., 23., 24., 13., 32., 38., 36.,
       32., 37., 20., 25., 29., 10., 21., 15., 20., 34., 18., 14., 14.,
       19., 33., 15., 34., 13., 13., 25., 16., 15., 18., 31., 26., 30.,
       18., 26., 28., 27., 30., 17., 34., 24., 21., 15., 13., 28., 25.,
       18., 22., 12., 11., 14., 16., 27., 25., 37., 10., 14., 18., 21.,
       38., 19., 34., 12., 34., 31., 15., 20., 14., 19., 31., 34., 15.,
       37., 22., 27., 38., 16., 15., 15., 25., 26., 14., 26., 18., 14.,
       21., 13., 23., 35., 18., 19., 16., 20., 39., 18., 12., 18., 19.,
       28., 21., 14., 13., 19., 22., 19., 24., 18., 27., 13., 27., 24.,
       26., 15., 26., 27., 30., 18., 27., 35., 24., 18., 30., 13

In [0]:
p_new = perm [int(len(f_old)):]
p_new

array([32., 18., 31., 16., 20., 28., 16., 14., 27., 34., 13., 38., 26.,
       12., 19., 30., 18., 31., 14., 29., 13., 13., 22., 18., 14., 32.,
       28., 32., 18., 39., 25., 14., 23., 14., 32., 19., 13., 24., 18.,
       19., 18., 45., 21., 32., 28., 38., 25., 15., 29., 33., 20., 22.,
       22., 14., 17., 36., 13., 31., 19., 22., 13., 39., 19., 19., 11.,
       41., 18., 12., 18., 24., 14., 27., 14., 16., 34., 29., 27., 20.,
       24.])

In [0]:
mean_p_old = np.mean(p_old)
mean_p_old

22.526104417670684

In [0]:
mean_p_new = np.mean(p_new)
mean_p_new

22.974683544303797

In [0]:
t_perm = mean_p_new - mean_p_old
t_perm

0.4485791266331134

In [0]:
t_obs = mean_new - mean_old
t_obs

10.336434344974837

In [0]:
#Since, the null-hypothesis assume that t_perm = t_obs, which is not the case here, we will reject the null hypothesis
# Lets check hypothesis 1
#check for p-value to reject the hypothesis